---
locale: es
tags: []
layout: input_bottom
editor: 0
type: interactive
extra_visible: true
teacher_info: ''
manual_evaluation: false
choices: []
goal: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  kind: last_query_outputs
  output: '{nombre:"Coliseo",locacion:"Roma, Italia",anioDeConstruccion:80}'
name: Los primeros registros
